direction: down

Terminal: "Terminal window" {
  Session: "tmux session" {
    Window1: "window 1" {
      Pane11: "pane 1"
      Pane12: "pane 2"
    }

    Window2: "window 2" {
      Pane21: "pane 1"
    }

    Window3: "window 3" {
      Pane31: "pane 1"
    }
  }
}
