settings.tex = "lualatex";
settings.outformat = "pdf";
settings.prc = false;
texpreamble("\usepackage{fontspec}");
texpreamble("\usepackage{amsmath}");
texpreamble("\usepackage{amsthm}");
texpreamble("\usepackage{xcolor}");
texpreamble("\usepackage{unicode-math}");
texpreamble("\setmainfont{Noto Sans}");
texpreamble("\setsansfont{Noto Sans}");
texpreamble("\setmathfont[Path=../fonts/,Extension=.ttf,]{NotoSansMath-Regular}");
import x11colors;

size(0,0);
pair A=0;
dot(A);
arrow("1",A,NE, 3cm);
arrow("2",A,SE, 2cm);
arrow("3",A,SW, 2.5cm, Margin(3,0));
arrow("4",A,NW, 2.5cm,N);
